//! Creature genomes: the parameter set every body and animation derives from.
//!
//! A creature is not an imported model, it is roughly two dozen numbers. That is
//! what makes the art pipeline work without an artist — but more usefully, it makes
//! bodies *heritable*. Children are generated by mixing their parents' genomes, so
//! family resemblance is visible from the god's-eye view long before the
//! simulation says anything about who is related to whom.

use crate::palette;
use crate::rng::Rng;

/// Body plans the generator knows how to build.
///
/// Kept deliberately coarse. The variation that matters is within a plan, not
/// between plans.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum Species {
    /// Two legs, two arms, clothed. Villagers.
    Human,
    /// Four legs, long neck, skittish. Prey.
    Deer,
    /// Four legs, low slung, fast. Predator.
    Wolf,
    /// Four legs, heavy, short. Stubborn.
    Boar,
    /// Long legs, long neck, a humped back. The desert's own.
    Camel,
    /// Heavy, slow, and not to be argued with. Woods and the north.
    Bear,
    /// The same again, bigger and white, and it keeps the far north.
    PolarBear,
    /// Upright, small, and it keeps the far SOUTH - see `wildlife::beasts_of`
    /// for why the two poles get different animals.
    Penguin,
    /// Green, short, and it keeps a camp. Wears a loincloth and hunts.
    Goblin,
}

impl Species {
    /// Whether this creature stands on two legs.
    ///
    /// NOT the same question as [`Species::is_human`], and keeping them apart
    /// is what lets a penguin exist. The skeleton is decided here; whether the
    /// thing wears clothes and grows hair is decided there.
    pub fn is_biped(self) -> bool {
        matches!(self, Species::Human | Species::Penguin | Species::Goblin)
    }

    /// Whether this creature is one of the village's own - the only kind that
    /// has an age, a hairstyle, a hat and a coat.
    pub fn is_human(self) -> bool {
        matches!(self, Species::Human)
    }

    /// Whether this creature hunts other creatures.
    ///
    /// Was a bare `== Wolf` in three places, which is exactly the shape of
    /// thing that goes stale the moment a second predator is added - and a bear
    /// that ambled past a deer without noticing would be the first thing
    /// anybody saw.
    pub fn hunts(self) -> bool {
        matches!(
            self,
            Species::Wolf | Species::Bear | Species::PolarBear | Species::Goblin
        )
    }

    #[allow(dead_code)]
    pub fn leg_count(self) -> usize {
        if self.is_biped() { 2 } else { 4 }
    }

    /// Base walking speed in world units per second.
    pub fn base_speed(self) -> f32 {
        match self {
            Species::Human => 2.4,
            Species::Deer => 4.2,
            Species::Wolf => 4.8,
            Species::Boar => 2.8,
            // A camel's walk is unhurried and covers ground anyway.
            Species::Camel => 3.2,
            // Bears look slow and are not. Under a wolf, over a boar - fast
            // enough that walking away from one is a decision.
            Species::Bear => 3.6,
            Species::PolarBear => 3.8,
            // A penguin on land is doing its worst work.
            Species::Penguin => 1.3,
            // Quicker than a villager on shorter legs, which is most of what
            // makes them a nuisance rather than a sight.
            Species::Goblin => 2.9,
        }
    }
}

impl Species {
    /// How tall a full-grown one stands, in meters, before its own roll.
    ///
    /// On the SPECIES rather than on a built genome, because the menagerie's
    /// caption has to name a size for a creature it may not have rolled yet -
    /// and because the framing there deliberately throws size away, holding
    /// the lens back a multiple of the subject's own height so that a penguin
    /// and a polar bear fill the frame identically.
    pub fn stands_about(self) -> f32 {
        match self {
            Species::Human => 1.75,
            Species::Deer => 1.5,
            Species::Wolf => 1.0,
            Species::Boar => 0.95,
            // Taller than a person, which is the whole of what a camel is on a
            // flat horizon.
            Species::Camel => 2.1,
            // At the shoulder, on all fours - a bear standing up would be half
            // again this, and standing up is not something the rig does.
            Species::Bear => 1.35,
            // AND THE BIGGEST THING THAT WALKS. Brett: "bigger polar bears!"
            // Half again a brown bear before its own scale roll, which on top
            // of a larger scale range makes the largest of them near enough
            // twice the animal - and taller at the shoulder than a villager is
            // tall.
            Species::PolarBear => 1.95,
            Species::Penguin => 0.8,
            // SHORTER THAN A VILLAGER, and by enough to read instantly when
            // one is standing next to one. Two thirds of a person.
            Species::Goblin => 1.15,
        }
    }
}

/// Biological sex. Half of who can bear a child with whom — which makes it
/// half of demography, and demography is what decides whether a village that
/// can die can also endure.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum Sex {
    Female,
    Male,
}

/// Life stage. Drives size, proportion and bearing.
///
/// The single biggest contributor to a crowd reading as a *population* rather than
/// as a batch of clones: a settlement of uniformly adult-sized figures looks
/// manufactured no matter how much its colors vary.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum Age {
    Child,
    Adult,
    Elder,
}

impl Age {
    /// Multiplier on total height.
    pub fn height_scale(self) -> f32 {
        match self {
            Age::Child => 0.62,
            Age::Adult => 1.0,
            Age::Elder => 0.94,
        }
    }

    /// Extra head size as a fraction of height. Children are famously top-heavy,
    /// and it is the clearest silhouette cue that one is a child.
    pub fn head_bonus(self) -> f32 {
        match self {
            Age::Child => 0.06,
            Age::Adult => 0.0,
            Age::Elder => 0.01,
        }
    }

    /// Multiplier on walking speed.
    pub fn pace(self) -> f32 {
        match self {
            Age::Child => 1.15,
            Age::Adult => 1.0,
            Age::Elder => 0.72,
        }
    }
}

/// How a villager wears their hair. Read almost entirely as silhouette.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum HairStyle {
    Bald,
    /// Close-cropped: a single thin slab over the crown.
    Cropped,
    /// Stacked slabs, taller than it is wide.
    Topknot,
    /// Falls behind the head, down the back of the neck.
    Long,
    /// Two blocks out to the sides.
    Tufts,
}

impl HairStyle {
    pub const ALL: [HairStyle; 5] = [
        HairStyle::Bald,
        HairStyle::Cropped,
        HairStyle::Topknot,
        HairStyle::Long,
        HairStyle::Tufts,
    ];
}

/// Something worn on the head.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum Headwear {
    None,
    /// A flat cap sitting on the crown.
    Cap,
    /// A hood enclosing the whole head.
    Hood,
    /// A narrow band around the brow.
    Band,
}

impl Headwear {
    pub const ALL: [Headwear; 4] = [
        Headwear::None,
        Headwear::Cap,
        Headwear::Hood,
        Headwear::Band,
    ];
}

/// Cut of clothing.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum Garment {
    /// Torso only; legs bare.
    Tunic,
    /// Torso plus a skirt falling over the thighs.
    Robe,
    /// Torso plus a contrasting sash across the chest.
    Wrap,
    /// A strip at the hips and nothing else. What goblins wear.
    Loincloth,
    /// A hide slung over one shoulder, with the strip beneath it.
    Pelt,
    /// Less than the strip, and males only.
    Clout,
}

impl Garment {
    /// What the village wears. The goblin cuts are deliberately not in it: a
    /// villager who rolled one would read as a goblin who had wandered in.
    pub const ALL: [Garment; 3] = [Garment::Tunic, Garment::Robe, Garment::Wrap];

    /// What a goblin wears.
    ///
    /// Three, because one was a uniform. A camp in identical dress reads as
    /// one goblin printed four times, and dress is most of what the eye has to
    /// go on at the distance a camp is usually seen from - the ears do the
    /// species, the clothes do the individual.
    pub const GOBLIN: [Garment; 3] = [Garment::Loincloth, Garment::Pelt, Garment::Clout];

    /// Whether this cut is worn by males only.
    ///
    /// One of the three is, which is a fact about the goblins rather than
    /// about the renderer, so it lives here beside the cuts themselves rather
    /// than as a condition buried in whoever happens to be rolling one.
    pub fn males_only(self) -> bool {
        matches!(self, Garment::Clout)
    }

    /// The cuts a goblin of this sex may be dealt.
    pub fn goblin_wardrobe(sex: Sex) -> Vec<Garment> {
        Garment::GOBLIN
            .into_iter()
            .filter(|cut| !cut.males_only() || sex == Sex::Male)
            .collect()
    }
}

/// Where a creature's head sits relative to its body, and how it carries itself.
#[derive(Clone, Copy, Debug, serde::Serialize, serde::Deserialize)]
pub struct Proportions {
    /// Overall size multiplier applied to every measurement.
    pub scale: f32,
    /// 0 is slender, 1 is broad. Drives torso and limb thickness.
    pub build: f32,
    /// Leg length as a fraction of total height.
    pub leg_length: f32,
    /// Arm length as a fraction of total height. Ignored for quadrupeds.
    pub arm_length: f32,
    /// Head edge length as a fraction of total height.
    pub head_size: f32,
    /// Torso length as a fraction of total height.
    pub torso_length: f32,
    /// Neck length. Near zero for humans, substantial for deer.
    pub neck_length: f32,
}

/// A color choice: which ramp, and how far up it.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub struct Tone {
    pub ramp: usize,
    pub step: usize,
}

impl Tone {
    pub fn palette_index(self) -> usize {
        palette::palette_index(self.ramp, self.step)
    }

    /// Shifts the tone darker or lighter within its own ramp, staying in bounds.
    /// Used for shading one body part against another without leaving the palette.
    pub fn shifted(self, delta: i32) -> Tone {
        let step = (self.step as i32 + delta).clamp(0, palette::RAMP_STEPS as i32 - 1);
        Tone {
            ramp: self.ramp,
            step: step as usize,
        }
    }
}

/// How a creature moves. Separated from proportions because gait reads as
/// personality, and we want to vary it independently of build.
#[derive(Clone, Copy, Debug, serde::Serialize, serde::Deserialize)]
pub struct Gait {
    /// Multiplier on stride frequency.
    pub stride_rate: f32,
    /// How far limbs swing, in radians.
    pub stride_swing: f32,
    /// Vertical bob per stride, in body heights.
    pub bounce: f32,
    /// Side-to-side sway per stride, in radians.
    pub sway: f32,
    /// Resting lean. Positive is hunched forward.
    pub lean: f32,
}

/// The complete description of one creature's body.
#[derive(Clone, Debug, bevy::prelude::Component, serde::Serialize, serde::Deserialize)]
pub struct CreatureGenome {
    pub species: Species,
    pub sex: Sex,
    pub proportions: Proportions,
    pub gait: Gait,
    pub skin: Tone,
    pub cloth: Tone,
    /// Second clothing color, for trim, belts, sashes and hoods. Drawn from a
    /// different ramp than `cloth` so the two always read as distinct.
    pub accent: Tone,
    pub hair: Tone,
    /// Life stage. Humans only; animals are always `Adult`.
    pub age: Age,
    pub hair_style: HairStyle,
    /// How many slabs the hairstyle stacks. Meaningless when bald.
    pub hair_volume: u8,
    pub beard: bool,
    pub headwear: Headwear,
    pub garment: Garment,
    /// A contrasting band at the waist.
    pub belt: bool,
    /// Legs clothed rather than bare.
    pub trousers: bool,
    /// A pack worn on the back.
    pub satchel: bool,
    /// Whether the creature has horns or antlers.
    pub horns: bool,
    /// Whether the creature has a tail.
    pub tail: bool,
    /// How far a goblin's ears tilt from horizontal, in radians. Positive is
    /// up, negative is down, zero is straight out the side.
    ///
    /// Per individual, because a camp of goblins wearing identical ears reads
    /// as a row of the same goblin - and the ears are the loudest thing about
    /// them, so they are the worst part to have in lockstep. Brett: "some have
    /// ears that are sticking slightly up so I'm having them straight out and
    /// still have them slightly down."
    ///
    /// `serde(default)` because this arrived after saves existed: an old
    /// genome loads with level ears rather than failing to load at all.
    #[serde(default)]
    pub ear_tilt: f32,
}

impl CreatureGenome {
    /// Generates a fresh, unrelated creature.
    pub fn random(species: Species, rng: &mut Rng) -> Self {
        let sex = if rng.chance(0.5) {
            Sex::Female
        } else {
            Sex::Male
        };

        // Rough demographics for a settlement rather than a uniform roll: mostly
        // working-age adults, a quarter children, a few elders.
        let age = if species.is_biped() {
            let roll = rng.f32();
            if roll < 0.24 {
                Age::Child
            } else if roll < 0.88 {
                Age::Adult
            } else {
                Age::Elder
            }
        } else {
            Age::Adult
        };
        Self::built(species, sex, age, rng)
    }

    /// A grown creature of a chosen sex - what a founding generation is
    /// made of. Sex and age reach into the body itself (build, leg length,
    /// the head's share of the height, whether a beard is possible), so
    /// they are chosen BEFORE it is grown rather than stamped on after.
    pub fn adult(species: Species, sex: Sex, rng: &mut Rng) -> Self {
        Self::built(species, sex, Age::Adult, rng)
    }

    fn built(species: Species, sex: Sex, age: Age, rng: &mut Rng) -> Self {
        let proportions = match species {
            // Deliberately not human proportions. Villagers are three or four
            // pixels tall at normal zoom, and a realiztically-proportioned figure
            // at that size is an unreadable smear. Oversized heads and short legs
            // are what let a silhouette still read as a person — the same reason
            // pixel artists have always drawn characters this way.
            Species::Human => Proportions {
                scale: rng.trait_value(0.86, 1.14),
                // A slight bias, not a rule: broad women and slight men both
                // exist, the distributions just don't sit in the same place.
                build: (rng.trait_value(0.0, 1.0) + if sex == Sex::Male { 0.08 } else { -0.06 })
                    .clamp(0.0, 1.0),
                // Children are short-legged as well as small, which is what stops
                // them reading as merely distant adults.
                leg_length: rng.trait_value(0.32, 0.39)
                    - if age == Age::Child { 0.04 } else { 0.0 },
                arm_length: rng.trait_value(0.28, 0.34),
                head_size: rng.trait_value(0.23, 0.28) + age.head_bonus(),
                torso_length: rng.trait_value(0.32, 0.38),
                neck_length: rng.trait_value(0.01, 0.03),
            },
            Species::Deer => Proportions {
                scale: rng.trait_value(0.9, 1.1),
                build: rng.trait_value(0.0, 0.45),
                leg_length: rng.trait_value(0.48, 0.58),
                arm_length: 0.0,
                head_size: rng.trait_value(0.13, 0.17),
                torso_length: rng.trait_value(0.38, 0.46),
                neck_length: rng.trait_value(0.16, 0.24),
            },
            Species::Wolf => Proportions {
                scale: rng.trait_value(0.85, 1.05),
                build: rng.trait_value(0.25, 0.6),
                leg_length: rng.trait_value(0.36, 0.44),
                arm_length: 0.0,
                head_size: rng.trait_value(0.16, 0.20),
                torso_length: rng.trait_value(0.44, 0.52),
                neck_length: rng.trait_value(0.06, 0.11),
            },
            Species::Boar => Proportions {
                scale: rng.trait_value(0.8, 1.0),
                build: rng.trait_value(0.6, 1.0),
                leg_length: rng.trait_value(0.26, 0.33),
                arm_length: 0.0,
                head_size: rng.trait_value(0.19, 0.24),
                torso_length: rng.trait_value(0.46, 0.55),
                neck_length: rng.trait_value(0.03, 0.07),
            },
            // All legs and neck. A camel reads at a distance by being TALLER
            // than everything around it and narrow with it - the silhouette is
            // the animal, and on a bare horizon it is all anybody gets.
            Species::Camel => Proportions {
                scale: rng.trait_value(0.95, 1.15),
                build: rng.trait_value(0.35, 0.65),
                leg_length: rng.trait_value(0.46, 0.54),
                arm_length: 0.0,
                head_size: rng.trait_value(0.12, 0.16),
                torso_length: rng.trait_value(0.34, 0.42),
                neck_length: rng.trait_value(0.22, 0.30),
            },
            // The opposite silhouette: low, long and thick, with a head that
            // carries. Short legs on a heavy body is the whole read.
            Species::Bear => Proportions {
                scale: rng.trait_value(0.9, 1.1),
                build: rng.trait_value(0.75, 1.0),
                leg_length: rng.trait_value(0.28, 0.35),
                arm_length: 0.0,
                head_size: rng.trait_value(0.20, 0.25),
                torso_length: rng.trait_value(0.50, 0.58),
                neck_length: rng.trait_value(0.04, 0.09),
            },
            // BIGGER. Brett asked for it by name, and the size is the point:
            // a polar bear that read as a pale brown bear would be a recolor.
            // Longer in the body and the neck than its cousin as well as
            // larger overall, which is what the real difference looks like.
            Species::PolarBear => Proportions {
                scale: rng.trait_value(1.05, 1.28),
                build: rng.trait_value(0.8, 1.0),
                leg_length: rng.trait_value(0.30, 0.37),
                arm_length: 0.0,
                head_size: rng.trait_value(0.17, 0.21),
                torso_length: rng.trait_value(0.54, 0.62),
                neck_length: rng.trait_value(0.09, 0.14),
            },
            // Upright, and almost all torso: the legs are stubs and the head
            // sits nearly on the shoulders. The arms are flippers, kept short
            // enough that the swing reads as a waddle.
            Species::Penguin => Proportions {
                scale: rng.trait_value(0.85, 1.15),
                build: rng.trait_value(0.55, 0.85),
                leg_length: rng.trait_value(0.14, 0.20),
                arm_length: rng.trait_value(0.26, 0.34),
                head_size: rng.trait_value(0.21, 0.26),
                torso_length: rng.trait_value(0.56, 0.66),
                neck_length: rng.trait_value(0.01, 0.03),
            },
            // A person's plan, wrongly proportioned on purpose: short legs, a
            // long reach and a head too big for either. Standing beside a
            // villager it should be obvious that this is NOT one, before the
            // color is read at all.
            Species::Goblin => Proportions {
                scale: rng.trait_value(0.88, 1.08),
                build: rng.trait_value(0.2, 0.55),
                leg_length: rng.trait_value(0.26, 0.32),
                arm_length: rng.trait_value(0.36, 0.44),
                head_size: rng.trait_value(0.26, 0.32),
                torso_length: rng.trait_value(0.30, 0.36),
                neck_length: rng.trait_value(0.01, 0.03),
            },
        };

        let gait = Gait {
            stride_rate: rng.trait_value(0.85, 1.2),
            stride_swing: match species {
                // Kept modest: a wide swing on short legs throws them past
                // horizontal and the villager reads as falling over rather than
                // walking.
                Species::Human => rng.trait_value(0.36, 0.56),
                Species::Deer => rng.trait_value(0.6, 0.95),
                Species::Wolf => rng.trait_value(0.65, 1.0),
                Species::Boar => rng.trait_value(0.4, 0.65),
                // Long legs, slow swing: a camel's walk is a saunter, and a
                // brisk one on those legs reads as a cartoon.
                Species::Camel => rng.trait_value(0.34, 0.52),
                Species::Bear | Species::PolarBear => rng.trait_value(0.30, 0.48),
                // THE WADDLE. A wide swing on very short legs is exactly the
                // thing the human arm is kept away from - and on a penguin it
                // is the whole charm, so it gets the widest swing in the game.
                Species::Penguin => rng.trait_value(0.9, 1.3),
                // Scurrying. Wider and faster than a villager's, which reads
                // as agitation even when they are only crossing a camp.
                Species::Goblin => rng.trait_value(0.55, 0.85),
            },
            bounce: rng.trait_value(0.012, 0.032),
            sway: rng.trait_value(0.02, 0.07),
            lean: match species {
                // Elders stoop. It costs one number and it is legible across the
                // whole valley.
                Species::Human => {
                    rng.trait_value(-0.04, 0.10) + if age == Age::Elder { 0.16 } else { 0.0 }
                }
                _ => rng.trait_value(-0.02, 0.05),
            },
        };

        let skin = match species {
            Species::Human => Tone {
                ramp: *rng.pick(palette::SKIN_RAMPS),
                step: rng.range_i(1, 4) as usize,
            },
            Species::Deer => Tone {
                ramp: palette::RAMP_EARTH,
                step: rng.range_i(2, 4) as usize,
            },
            Species::Wolf => Tone {
                ramp: palette::RAMP_STONE,
                step: rng.range_i(1, 3) as usize,
            },
            Species::Boar => Tone {
                ramp: palette::RAMP_EARTH,
                step: rng.range_i(1, 3) as usize,
            },
            Species::Camel => Tone {
                ramp: palette::RAMP_SAND,
                step: rng.range_i(2, 4) as usize,
            },
            Species::Bear => Tone {
                ramp: palette::RAMP_WOOD,
                step: rng.range_i(0, 2) as usize,
            },
            // Not white - nothing in this game is. The snow ramp's upper steps
            // are a cold off-white, which is what a polar bear actually is
            // against actual snow: a shade warmer than the ground it stands on.
            Species::PolarBear => Tone {
                ramp: palette::RAMP_SNOW,
                step: rng.range_i(2, 4) as usize,
            },
            // The DARK half of the penguin - head and back. Its front is the
            // `cloth` tone below, which is the one part of the clothing system
            // an animal still uses: a penguin is the one creature in the world
            // that really is two-tone.
            Species::Penguin => Tone {
                ramp: palette::RAMP_STONE,
                step: rng.range_i(0, 1) as usize,
            },
            // GREEN, off the foliage ramp rather than a color of its own -
            // this world's greens all come from one family, and a goblin the
            // palette had never met would read as pasted in. The lower steps,
            // so they are the dark green of the wood's underside rather than
            // the bright green of a leaf in the sun.
            Species::Goblin => Tone {
                ramp: palette::RAMP_FOLIAGE,
                // The UPPER steps. The lower ones are the near-black green of
                // a wood's underside, and a goblin wearing them read as a dark
                // smudge rather than as a green person - which is the one
                // thing about them that has to land at a glance.
                step: rng.range_i(2, 4) as usize,
            },
        };

        let cloth = match species {
            // A PENGUIN'S FRONT. `cloth` dresses the torso of anything that
            // stands upright, and the one animal that does is also the one
            // animal that really is two-tone - so the coat it happens to
            // inherit from the clothing system is its own white bib, and the
            // dark `skin` above it is its head and back.
            Species::Penguin => Tone {
                ramp: palette::RAMP_BONE,
                step: rng.range_i(3, 4) as usize,
            },
            // Whatever a goblin found. Off the earth and wood ramps, low
            // steps: this is hide and sacking, not dyed cloth, and it must
            // never look like something the village wove.
            Species::Goblin => Tone {
                ramp: *rng.pick(&[palette::RAMP_EARTH, palette::RAMP_WOOD]),
                step: rng.range_i(0, 2) as usize,
            },
            _ => Tone {
                ramp: *rng.pick(palette::CLOTH_RAMPS),
                step: rng.range_i(1, 4) as usize,
            },
        };

        // Accent must not land on the same ramp as the main garment, or trim and
        // belts vanish into the cloth they are supposed to break up.
        let accent = {
            let mut tone = Tone {
                ramp: *rng.pick(palette::CLOTH_RAMPS),
                step: rng.range_i(1, 4) as usize,
            };
            for _ in 0..8 {
                if tone.ramp != cloth.ramp {
                    break;
                }
                tone.ramp = *rng.pick(palette::CLOTH_RAMPS);
            }
            tone
        };

        // Elders gray. Sampling the bone ramp rather than a dedicated gray keeps it
        // inside the palette.
        let hair = if age == Age::Elder && rng.chance(0.8) {
            Tone {
                ramp: palette::RAMP_BONE,
                step: rng.range_i(3, 4) as usize,
            }
        } else {
            Tone {
                ramp: *rng.pick(palette::HAIR_RAMPS),
                step: rng.range_i(0, 3) as usize,
            }
        };

        // IS_HUMAN, not IS_BIPED, and the difference is a penguin in a hat.
        // These two questions were the same one while the village was the only
        // thing that stood upright; the moment something else did, every
        // hairstyle, coat and satchel in the wardrobe was offered to it.
        let human = species.is_human();

        CreatureGenome {
            species,
            sex,
            proportions,
            gait,
            skin,
            cloth,
            accent,
            hair,
            age,
            hair_style: if human {
                *rng.pick(&HairStyle::ALL)
            } else {
                HairStyle::Bald
            },
            hair_volume: rng.range_i(1, 3) as u8,
            // Beards on grown men only.
            beard: human && sex == Sex::Male && age != Age::Child && rng.chance(0.45),
            headwear: if human {
                *rng.pick(&Headwear::ALL)
            } else {
                Headwear::None
            },
            garment: match species {
                // Dealt from the goblins' own wardrobe, which is three cuts
                // and not the village's - and one of the three is males only,
                // so the roll is made against what this one may actually wear
                // rather than rolled and then corrected.
                Species::Goblin => *rng.pick(&Garment::goblin_wardrobe(sex)),
                _ if human => *rng.pick(&Garment::ALL),
                _ => Garment::Tunic,
            },
            belt: human && rng.chance(0.45),
            trousers: human && rng.chance(0.5),
            satchel: human && age == Age::Adult && rng.chance(0.25),
            horns: match species {
                Species::Deer => rng.chance(0.5),
                Species::Boar => rng.chance(0.8),
                _ => false,
            },
            // Everything that is not one of the village's own has a tail -
            // except the penguin, whose tail at this scale is a smudge on the
            // back of a bird that is already mostly torso.
            tail: !species.is_human() && species != Species::Penguin,
            // A wide spread, and deliberately not centered on level: more of
            // them prick up than droop, so a camp reads as alert.
            ear_tilt: rng.trait_value(-0.25, 0.75),
        }
    }

    /// Generates a child from two parents.
    ///
    /// Continuous traits average with a mutation nudge; discrete traits are
    /// inherited whole from one parent or the other. That produces children who
    /// are recognizably of their parents without being an exact blend of them.
    // Exercised by tests; wired into the simulation when births land.
    #[allow(dead_code)]
    pub fn child_of(a: &CreatureGenome, b: &CreatureGenome, rng: &mut Rng) -> Self {
        debug_assert_eq!(
            a.species, b.species,
            "cross-species inheritance is not defined",
        );

        // Mixes two values, biased toward one parent, with a small mutation.
        let mut mix = |x: f32, y: f32, spread: f32| {
            let bias = rng.range(0.3, 0.7);
            let blended = x + (y - x) * bias;
            blended + rng.gaussian() * spread
        };

        let proportions = Proportions {
            scale: mix(a.proportions.scale, b.proportions.scale, 0.03).clamp(0.7, 1.3),
            build: mix(a.proportions.build, b.proportions.build, 0.06).clamp(0.0, 1.0),
            leg_length: mix(a.proportions.leg_length, b.proportions.leg_length, 0.012)
                .clamp(0.22, 0.60),
            arm_length: mix(a.proportions.arm_length, b.proportions.arm_length, 0.012)
                .clamp(0.0, 0.45),
            head_size: mix(a.proportions.head_size, b.proportions.head_size, 0.008)
                .clamp(0.12, 0.26),
            torso_length: mix(
                a.proportions.torso_length,
                b.proportions.torso_length,
                0.012,
            )
            .clamp(0.28, 0.58),
            neck_length: mix(a.proportions.neck_length, b.proportions.neck_length, 0.008)
                .clamp(0.0, 0.28),
        };

        let gait = Gait {
            stride_rate: mix(a.gait.stride_rate, b.gait.stride_rate, 0.04).clamp(0.7, 1.4),
            stride_swing: mix(a.gait.stride_swing, b.gait.stride_swing, 0.05).clamp(0.3, 1.1),
            bounce: mix(a.gait.bounce, b.gait.bounce, 0.004).clamp(0.005, 0.045),
            sway: mix(a.gait.sway, b.gait.sway, 0.008).clamp(0.0, 0.1),
            lean: mix(a.gait.lean, b.gait.lean, 0.015).clamp(-0.1, 0.16),
        };

        // Skin inherits a ramp from one parent but may land between their steps,
        // which is what makes siblings vary without ever leaving the palette.
        let skin_parent = if rng.chance(0.5) { a } else { b };
        let other = if std::ptr::eq(skin_parent, a) { b } else { a };
        let skin_step = if skin_parent.skin.ramp == other.skin.ramp {
            let lo = skin_parent.skin.step.min(other.skin.step) as i32;
            let hi = skin_parent.skin.step.max(other.skin.step) as i32;
            rng.range_i(lo, hi) as usize
        } else {
            skin_parent.skin.step
        };

        let cloth = Tone {
            ramp: *rng.pick(palette::CLOTH_RAMPS),
            step: rng.range_i(1, 4) as usize,
        };
        let accent = {
            let mut tone = Tone {
                ramp: *rng.pick(palette::CLOTH_RAMPS),
                step: rng.range_i(1, 4) as usize,
            };
            for _ in 0..8 {
                if tone.ramp != cloth.ramp {
                    break;
                }
                tone.ramp = *rng.pick(palette::CLOTH_RAMPS);
            }
            tone
        };

        CreatureGenome {
            species: a.species,
            // An even roll, independent of the parents.
            sex: if rng.chance(0.5) {
                Sex::Female
            } else {
                Sex::Male
            },
            proportions,
            gait,
            skin: Tone {
                ramp: skin_parent.skin.ramp,
                step: skin_step,
            },
            // Clothing, headwear and grooming are cultural, not genetic, so they are
            // re-rolled rather than inherited. When settlements gain doctrine, this
            // is where it will express itself — a village that decides the god
            // favors the drowned will dress differently from one that does not.
            cloth,
            accent,
            hair: if rng.chance(0.5) { a.hair } else { b.hair },
            // A newborn is a child; ageing happens in the simulation, not here.
            age: Age::Child,
            hair_style: *rng.pick(&HairStyle::ALL),
            hair_volume: if rng.chance(0.5) {
                a.hair_volume
            } else {
                b.hair_volume
            },
            beard: false,
            headwear: *rng.pick(&Headwear::ALL),
            garment: *rng.pick(&Garment::ALL),
            belt: rng.chance(0.45),
            trousers: rng.chance(0.5),
            satchel: false,
            horns: if rng.chance(0.5) { a.horns } else { b.horns },
            tail: a.tail,
            ear_tilt: (a.ear_tilt + b.ear_tilt) * 0.5,
        }
    }

    /// Total standing height in world units.
    pub fn height(&self) -> f32 {
        let p = &self.proportions;
        let base = self.species.stands_about();
        // Age scales the finished height rather than being folded into `scale`, so
        // an inherited `scale` always means "size as an adult". Otherwise a child's
        // own smallness would be passed on to its children and the line would shrink
        // every generation.
        base * p.scale * self.age.height_scale()
    }

    /// Limb and torso thickness in world units.
    pub fn thickness(&self) -> f32 {
        let p = &self.proportions;
        self.height() * (0.07 + p.build * 0.05)
    }

    /// Walking speed in world units per second.
    pub fn walk_speed(&self) -> f32 {
        self.species.base_speed() * self.proportions.scale * self.gait.stride_rate * self.age.pace()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample(species: Species, seed: u64) -> CreatureGenome {
        CreatureGenome::random(species, &mut Rng::new(seed))
    }

    #[test]
    fn women_are_never_bearded_and_grown_men_often_are() {
        let mut bearded_men = 0;
        for seed in 0..300 {
            let g = sample(Species::Human, seed);
            match g.sex {
                Sex::Female => assert!(!g.beard, "a bearded woman at seed {seed}"),
                Sex::Male if g.age != Age::Child && g.beard => bearded_men += 1,
                Sex::Male => {}
            }
        }
        assert!(bearded_men > 20, "only {bearded_men} bearded men in 300");
    }

    #[test]
    fn both_sexes_are_born_in_roughly_even_measure() {
        let mother = sample(Species::Human, 1);
        let father = sample(Species::Human, 2);
        let mut rng = Rng::new(9);
        let mut daughters = 0;
        for _ in 0..200 {
            let child = CreatureGenome::child_of(&mother, &father, &mut rng);
            if child.sex == Sex::Female {
                daughters += 1;
            }
        }
        assert!(
            (60..=140).contains(&daughters),
            "{daughters} daughters of 200",
        );
    }

    #[test]
    fn generation_is_deterministic() {
        let a = sample(Species::Human, 5);
        let b = sample(Species::Human, 5);
        assert_eq!(a.height(), b.height());
        assert_eq!(a.skin, b.skin);
    }

    #[test]
    fn every_species_produces_sane_bodies() {
        for species in [Species::Human, Species::Deer, Species::Wolf, Species::Boar] {
            for seed in 0..200 {
                let g = sample(species, seed);
                assert!(g.height() > 0.4 && g.height() < 3.0, "{species:?} height");
                assert!(g.thickness() > 0.0);
                assert!(g.walk_speed() > 0.0);
                assert!(g.proportions.leg_length > 0.0);
                assert!(g.skin.palette_index() < palette::PALETTE_LEN);
                assert!(g.cloth.palette_index() < palette::PALETTE_LEN);
                assert!(g.hair.palette_index() < palette::PALETTE_LEN);
            }
        }
    }

    #[test]
    fn only_humans_are_dressed_and_only_animals_have_tails() {
        for seed in 0..200 {
            let human = sample(Species::Human, seed);
            assert!(!human.tail);

            let wolf = sample(Species::Wolf, seed);
            assert!(wolf.tail);
            assert_eq!(wolf.hair_style, HairStyle::Bald);
            assert_eq!(wolf.headwear, Headwear::None);
            assert!(!wolf.beard && !wolf.belt && !wolf.trousers && !wolf.satchel);
            assert_eq!(wolf.age, Age::Adult);
        }
    }

    #[test]
    fn children_are_smaller_and_never_bearded() {
        let mut children = 0;
        for seed in 0..600 {
            let g = sample(Species::Human, seed);
            if g.age == Age::Child {
                children += 1;
                assert!(!g.beard, "seed {seed}: bearded child");
                assert!(!g.satchel);
            }
        }
        assert!(children > 60, "only {children} children in 600 villagers");
    }

    #[test]
    fn a_settlement_contains_every_life_stage() {
        // A crowd of uniformly adult figures reads as manufactured. Twelve villagers
        // will not always cover all three, but a few hundred must.
        let mut rng = Rng::new(2024);
        let mut saw = [false; 3];
        for _ in 0..300 {
            match CreatureGenome::random(Species::Human, &mut rng).age {
                Age::Child => saw[0] = true,
                Age::Adult => saw[1] = true,
                Age::Elder => saw[2] = true,
            }
        }
        assert!(saw.iter().all(|s| *s), "missing a life stage: {saw:?}");
    }

    #[test]
    fn accent_never_matches_the_main_garment() {
        // Trim, belts and sashes exist to break up the garment. Same ramp and they
        // disappear into it.
        for seed in 0..2_000 {
            let g = sample(Species::Human, seed);
            assert_ne!(g.accent.ramp, g.cloth.ramp, "seed {seed}");
        }
    }

    #[test]
    fn villagers_are_visually_distinct() {
        // The point of all of this: a settlement should not contain twins. Compare
        // the traits that actually read on screen.
        let mut rng = Rng::new(7);
        let mut seen = std::collections::HashSet::new();
        let population = 200;

        for _ in 0..population {
            let g = CreatureGenome::random(Species::Human, &mut rng);
            seen.insert((
                g.age,
                g.hair_style,
                g.headwear,
                g.garment,
                g.skin.ramp,
                g.skin.step,
                g.cloth.ramp,
                g.cloth.step,
                g.beard,
                g.trousers,
                g.belt,
            ));
        }

        // Allowing for chance collisions, near-all of them should be unique.
        assert!(
            seen.len() > (population * 9) / 10,
            "only {} distinct villagers out of {population}",
            seen.len(),
        );
    }

    #[test]
    fn children_resemble_their_parents() {
        // A child's height should sit near its parents' rather than anywhere in
        // the species range, otherwise family resemblance will not read on screen.
        let mut rng = Rng::new(1234);
        let mut close = 0;
        let trials = 800;

        for _ in 0..trials {
            let a = CreatureGenome::random(Species::Human, &mut rng);
            let b = CreatureGenome::random(Species::Human, &mut rng);
            let child = CreatureGenome::child_of(&a, &b, &mut rng);

            let parent_mid = (a.height() + b.height()) * 0.5;
            let spread = (a.height() - b.height()).abs().max(0.05);
            // Children are generated at child scale; compare grown-up sizes.
            let grown = child.height() / child.age.height_scale();
            if (grown - parent_mid).abs() <= spread {
                close += 1;
            }
        }

        let fraction = close as f32 / trials as f32;
        // The mutation nudge legitimately carries some children outside their
        // parents' spread; what this guards is the failure mode where height is
        // rolled fresh and the fraction collapses toward the species-wide rate.
        assert!(
            fraction > 0.7,
            "only {fraction} of children resembled parents"
        );
    }

    #[test]
    fn children_stay_within_valid_bounds() {
        let mut rng = Rng::new(99);
        let mut a = CreatureGenome::random(Species::Human, &mut rng);
        let mut b = CreatureGenome::random(Species::Human, &mut rng);

        // Breed many generations deep: drift must not walk the population off a cliff.
        for _ in 0..500 {
            let child = CreatureGenome::child_of(&a, &b, &mut rng);
            assert!(child.height() > 0.3 && child.height() < 3.0);
            assert!(child.proportions.build >= 0.0 && child.proportions.build <= 1.0);
            assert!(child.gait.stride_rate > 0.0);
            assert!(child.skin.palette_index() < palette::PALETTE_LEN);
            a = b;
            b = child;
        }
    }

    #[test]
    fn tone_shifting_stays_inside_the_ramp() {
        let t = Tone {
            ramp: palette::RAMP_GRASS,
            step: 2,
        };
        assert_eq!(t.shifted(-10).step, 0);
        assert_eq!(t.shifted(10).step, palette::RAMP_STEPS - 1);
        assert_eq!(t.shifted(1).step, 3);
        assert_eq!(t.shifted(0).ramp, palette::RAMP_GRASS);
    }
}
