//! Creature genomes: the parameter set every body and animation derives from.
//!
//! A creature is not an imported model, it is roughly two dozen numbers. That is
//! what makes the art pipeline work without an artist — but more usefully, it makes
//! bodies *heritable*. Children are generated by mixing their parents' genomes, so
//! family resemblance is visible from the god's-eye view long before the
//! simulation says anything about who is related to whom.

use crate::palette;
use crate::rng::Rng;

/// Body plans the generator knows how to build.
///
/// Kept deliberately coarse. The variation that matters is within a plan, not
/// between plans.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum Species {
    /// Two legs, two arms, clothed. Villagers.
    Human,
    /// Four legs, long neck, skittish. Prey.
    Deer,
    /// Four legs, low slung, fast. Predator.
    Wolf,
    /// Four legs, heavy, short. Stubborn.
    Boar,
}

impl Species {
    pub fn is_biped(self) -> bool {
        matches!(self, Species::Human)
    }

    #[allow(dead_code)]
    pub fn leg_count(self) -> usize {
        if self.is_biped() { 2 } else { 4 }
    }

    /// Base walking speed in world units per second.
    pub fn base_speed(self) -> f32 {
        match self {
            Species::Human => 2.4,
            Species::Deer => 4.2,
            Species::Wolf => 4.8,
            Species::Boar => 2.8,
        }
    }
}

/// Biological sex. Half of who can bear a child with whom — which makes it
/// half of demography, and demography is what decides whether a village that
/// can die can also endure.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum Sex {
    Female,
    Male,
}

/// Life stage. Drives size, proportion and bearing.
///
/// The single biggest contributor to a crowd reading as a *population* rather than
/// as a batch of clones: a settlement of uniformly adult-sized figures looks
/// manufactured no matter how much its colours vary.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum Age {
    Child,
    Adult,
    Elder,
}

impl Age {
    /// Multiplier on total height.
    pub fn height_scale(self) -> f32 {
        match self {
            Age::Child => 0.62,
            Age::Adult => 1.0,
            Age::Elder => 0.94,
        }
    }

    /// Extra head size as a fraction of height. Children are famously top-heavy,
    /// and it is the clearest silhouette cue that one is a child.
    pub fn head_bonus(self) -> f32 {
        match self {
            Age::Child => 0.06,
            Age::Adult => 0.0,
            Age::Elder => 0.01,
        }
    }

    /// Multiplier on walking speed.
    pub fn pace(self) -> f32 {
        match self {
            Age::Child => 1.15,
            Age::Adult => 1.0,
            Age::Elder => 0.72,
        }
    }
}

/// How a villager wears their hair. Read almost entirely as silhouette.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum HairStyle {
    Bald,
    /// Close-cropped: a single thin slab over the crown.
    Cropped,
    /// Stacked slabs, taller than it is wide.
    Topknot,
    /// Falls behind the head, down the back of the neck.
    Long,
    /// Two blocks out to the sides.
    Tufts,
}

impl HairStyle {
    pub const ALL: [HairStyle; 5] = [
        HairStyle::Bald,
        HairStyle::Cropped,
        HairStyle::Topknot,
        HairStyle::Long,
        HairStyle::Tufts,
    ];
}

/// Something worn on the head.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum Headwear {
    None,
    /// A flat cap sitting on the crown.
    Cap,
    /// A hood enclosing the whole head.
    Hood,
    /// A narrow band around the brow.
    Band,
}

impl Headwear {
    pub const ALL: [Headwear; 4] = [
        Headwear::None,
        Headwear::Cap,
        Headwear::Hood,
        Headwear::Band,
    ];
}

/// Cut of clothing.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum Garment {
    /// Torso only; legs bare.
    Tunic,
    /// Torso plus a skirt falling over the thighs.
    Robe,
    /// Torso plus a contrasting sash across the chest.
    Wrap,
}

impl Garment {
    pub const ALL: [Garment; 3] = [Garment::Tunic, Garment::Robe, Garment::Wrap];
}

/// Where a creature's head sits relative to its body, and how it carries itself.
#[derive(Clone, Copy, Debug, serde::Serialize, serde::Deserialize)]
pub struct Proportions {
    /// Overall size multiplier applied to every measurement.
    pub scale: f32,
    /// 0 is slender, 1 is broad. Drives torso and limb thickness.
    pub build: f32,
    /// Leg length as a fraction of total height.
    pub leg_length: f32,
    /// Arm length as a fraction of total height. Ignored for quadrupeds.
    pub arm_length: f32,
    /// Head edge length as a fraction of total height.
    pub head_size: f32,
    /// Torso length as a fraction of total height.
    pub torso_length: f32,
    /// Neck length. Near zero for humans, substantial for deer.
    pub neck_length: f32,
}

/// A colour choice: which ramp, and how far up it.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub struct Tone {
    pub ramp: usize,
    pub step: usize,
}

impl Tone {
    pub fn palette_index(self) -> usize {
        palette::palette_index(self.ramp, self.step)
    }

    /// Shifts the tone darker or lighter within its own ramp, staying in bounds.
    /// Used for shading one body part against another without leaving the palette.
    pub fn shifted(self, delta: i32) -> Tone {
        let step = (self.step as i32 + delta).clamp(0, palette::RAMP_STEPS as i32 - 1);
        Tone {
            ramp: self.ramp,
            step: step as usize,
        }
    }
}

/// How a creature moves. Separated from proportions because gait reads as
/// personality, and we want to vary it independently of build.
#[derive(Clone, Copy, Debug, serde::Serialize, serde::Deserialize)]
pub struct Gait {
    /// Multiplier on stride frequency.
    pub stride_rate: f32,
    /// How far limbs swing, in radians.
    pub stride_swing: f32,
    /// Vertical bob per stride, in body heights.
    pub bounce: f32,
    /// Side-to-side sway per stride, in radians.
    pub sway: f32,
    /// Resting lean. Positive is hunched forward.
    pub lean: f32,
}

/// The complete description of one creature's body.
#[derive(Clone, Debug, bevy::prelude::Component, serde::Serialize, serde::Deserialize)]
pub struct CreatureGenome {
    pub species: Species,
    pub sex: Sex,
    pub proportions: Proportions,
    pub gait: Gait,
    pub skin: Tone,
    pub cloth: Tone,
    /// Second clothing colour, for trim, belts, sashes and hoods. Drawn from a
    /// different ramp than `cloth` so the two always read as distinct.
    pub accent: Tone,
    pub hair: Tone,
    /// Life stage. Humans only; animals are always `Adult`.
    pub age: Age,
    pub hair_style: HairStyle,
    /// How many slabs the hairstyle stacks. Meaningless when bald.
    pub hair_volume: u8,
    pub beard: bool,
    pub headwear: Headwear,
    pub garment: Garment,
    /// A contrasting band at the waist.
    pub belt: bool,
    /// Legs clothed rather than bare.
    pub trousers: bool,
    /// A pack worn on the back.
    pub satchel: bool,
    /// Whether the creature has horns or antlers.
    pub horns: bool,
    /// Whether the creature has a tail.
    pub tail: bool,
}

impl CreatureGenome {
    /// Generates a fresh, unrelated creature.
    pub fn random(species: Species, rng: &mut Rng) -> Self {
        let sex = if rng.chance(0.5) {
            Sex::Female
        } else {
            Sex::Male
        };

        // Rough demographics for a settlement rather than a uniform roll: mostly
        // working-age adults, a quarter children, a few elders.
        let age = if species.is_biped() {
            let roll = rng.f32();
            if roll < 0.24 {
                Age::Child
            } else if roll < 0.88 {
                Age::Adult
            } else {
                Age::Elder
            }
        } else {
            Age::Adult
        };

        let proportions = match species {
            // Deliberately not human proportions. Villagers are three or four
            // pixels tall at normal zoom, and a realistically-proportioned figure
            // at that size is an unreadable smear. Oversized heads and short legs
            // are what let a silhouette still read as a person — the same reason
            // pixel artists have always drawn characters this way.
            Species::Human => Proportions {
                scale: rng.trait_value(0.86, 1.14),
                // A slight bias, not a rule: broad women and slight men both
                // exist, the distributions just don't sit in the same place.
                build: (rng.trait_value(0.0, 1.0) + if sex == Sex::Male { 0.08 } else { -0.06 })
                    .clamp(0.0, 1.0),
                // Children are short-legged as well as small, which is what stops
                // them reading as merely distant adults.
                leg_length: rng.trait_value(0.32, 0.39)
                    - if age == Age::Child { 0.04 } else { 0.0 },
                arm_length: rng.trait_value(0.28, 0.34),
                head_size: rng.trait_value(0.23, 0.28) + age.head_bonus(),
                torso_length: rng.trait_value(0.32, 0.38),
                neck_length: rng.trait_value(0.01, 0.03),
            },
            Species::Deer => Proportions {
                scale: rng.trait_value(0.9, 1.1),
                build: rng.trait_value(0.0, 0.45),
                leg_length: rng.trait_value(0.48, 0.58),
                arm_length: 0.0,
                head_size: rng.trait_value(0.13, 0.17),
                torso_length: rng.trait_value(0.38, 0.46),
                neck_length: rng.trait_value(0.16, 0.24),
            },
            Species::Wolf => Proportions {
                scale: rng.trait_value(0.85, 1.05),
                build: rng.trait_value(0.25, 0.6),
                leg_length: rng.trait_value(0.36, 0.44),
                arm_length: 0.0,
                head_size: rng.trait_value(0.16, 0.20),
                torso_length: rng.trait_value(0.44, 0.52),
                neck_length: rng.trait_value(0.06, 0.11),
            },
            Species::Boar => Proportions {
                scale: rng.trait_value(0.8, 1.0),
                build: rng.trait_value(0.6, 1.0),
                leg_length: rng.trait_value(0.26, 0.33),
                arm_length: 0.0,
                head_size: rng.trait_value(0.19, 0.24),
                torso_length: rng.trait_value(0.46, 0.55),
                neck_length: rng.trait_value(0.03, 0.07),
            },
        };

        let gait = Gait {
            stride_rate: rng.trait_value(0.85, 1.2),
            stride_swing: match species {
                // Kept modest: a wide swing on short legs throws them past
                // horizontal and the villager reads as falling over rather than
                // walking.
                Species::Human => rng.trait_value(0.36, 0.56),
                Species::Deer => rng.trait_value(0.6, 0.95),
                Species::Wolf => rng.trait_value(0.65, 1.0),
                Species::Boar => rng.trait_value(0.4, 0.65),
            },
            bounce: rng.trait_value(0.012, 0.032),
            sway: rng.trait_value(0.02, 0.07),
            lean: match species {
                // Elders stoop. It costs one number and it is legible across the
                // whole valley.
                Species::Human => {
                    rng.trait_value(-0.04, 0.10) + if age == Age::Elder { 0.16 } else { 0.0 }
                }
                _ => rng.trait_value(-0.02, 0.05),
            },
        };

        let skin = match species {
            Species::Human => Tone {
                ramp: *rng.pick(palette::SKIN_RAMPS),
                step: rng.range_i(1, 4) as usize,
            },
            Species::Deer => Tone {
                ramp: palette::RAMP_EARTH,
                step: rng.range_i(2, 4) as usize,
            },
            Species::Wolf => Tone {
                ramp: palette::RAMP_STONE,
                step: rng.range_i(1, 3) as usize,
            },
            Species::Boar => Tone {
                ramp: palette::RAMP_EARTH,
                step: rng.range_i(1, 3) as usize,
            },
        };

        let cloth = Tone {
            ramp: *rng.pick(palette::CLOTH_RAMPS),
            step: rng.range_i(1, 4) as usize,
        };

        // Accent must not land on the same ramp as the main garment, or trim and
        // belts vanish into the cloth they are supposed to break up.
        let accent = {
            let mut tone = Tone {
                ramp: *rng.pick(palette::CLOTH_RAMPS),
                step: rng.range_i(1, 4) as usize,
            };
            for _ in 0..8 {
                if tone.ramp != cloth.ramp {
                    break;
                }
                tone.ramp = *rng.pick(palette::CLOTH_RAMPS);
            }
            tone
        };

        // Elders grey. Sampling the bone ramp rather than a dedicated grey keeps it
        // inside the palette.
        let hair = if age == Age::Elder && rng.chance(0.8) {
            Tone {
                ramp: palette::RAMP_BONE,
                step: rng.range_i(3, 4) as usize,
            }
        } else {
            Tone {
                ramp: *rng.pick(palette::HAIR_RAMPS),
                step: rng.range_i(0, 3) as usize,
            }
        };

        let human = species.is_biped();

        CreatureGenome {
            species,
            sex,
            proportions,
            gait,
            skin,
            cloth,
            accent,
            hair,
            age,
            hair_style: if human {
                *rng.pick(&HairStyle::ALL)
            } else {
                HairStyle::Bald
            },
            hair_volume: rng.range_i(1, 3) as u8,
            // Beards on grown men only.
            beard: human && sex == Sex::Male && age != Age::Child && rng.chance(0.45),
            headwear: if human {
                *rng.pick(&Headwear::ALL)
            } else {
                Headwear::None
            },
            garment: if human {
                *rng.pick(&Garment::ALL)
            } else {
                Garment::Tunic
            },
            belt: human && rng.chance(0.45),
            trousers: human && rng.chance(0.5),
            satchel: human && age == Age::Adult && rng.chance(0.25),
            horns: match species {
                Species::Deer => rng.chance(0.5),
                Species::Boar => rng.chance(0.8),
                _ => false,
            },
            tail: species != Species::Human,
        }
    }

    /// Generates a child from two parents.
    ///
    /// Continuous traits average with a mutation nudge; discrete traits are
    /// inherited whole from one parent or the other. That produces children who
    /// are recognisably of their parents without being an exact blend of them.
    // Exercised by tests; wired into the simulation when births land.
    #[allow(dead_code)]
    pub fn child_of(a: &CreatureGenome, b: &CreatureGenome, rng: &mut Rng) -> Self {
        debug_assert_eq!(
            a.species, b.species,
            "cross-species inheritance is not defined",
        );

        // Mixes two values, biased toward one parent, with a small mutation.
        let mut mix = |x: f32, y: f32, spread: f32| {
            let bias = rng.range(0.3, 0.7);
            let blended = x + (y - x) * bias;
            blended + rng.gaussian() * spread
        };

        let proportions = Proportions {
            scale: mix(a.proportions.scale, b.proportions.scale, 0.03).clamp(0.7, 1.3),
            build: mix(a.proportions.build, b.proportions.build, 0.06).clamp(0.0, 1.0),
            leg_length: mix(a.proportions.leg_length, b.proportions.leg_length, 0.012)
                .clamp(0.22, 0.60),
            arm_length: mix(a.proportions.arm_length, b.proportions.arm_length, 0.012)
                .clamp(0.0, 0.45),
            head_size: mix(a.proportions.head_size, b.proportions.head_size, 0.008)
                .clamp(0.12, 0.26),
            torso_length: mix(
                a.proportions.torso_length,
                b.proportions.torso_length,
                0.012,
            )
            .clamp(0.28, 0.58),
            neck_length: mix(a.proportions.neck_length, b.proportions.neck_length, 0.008)
                .clamp(0.0, 0.28),
        };

        let gait = Gait {
            stride_rate: mix(a.gait.stride_rate, b.gait.stride_rate, 0.04).clamp(0.7, 1.4),
            stride_swing: mix(a.gait.stride_swing, b.gait.stride_swing, 0.05).clamp(0.3, 1.1),
            bounce: mix(a.gait.bounce, b.gait.bounce, 0.004).clamp(0.005, 0.045),
            sway: mix(a.gait.sway, b.gait.sway, 0.008).clamp(0.0, 0.1),
            lean: mix(a.gait.lean, b.gait.lean, 0.015).clamp(-0.1, 0.16),
        };

        // Skin inherits a ramp from one parent but may land between their steps,
        // which is what makes siblings vary without ever leaving the palette.
        let skin_parent = if rng.chance(0.5) { a } else { b };
        let other = if std::ptr::eq(skin_parent, a) { b } else { a };
        let skin_step = if skin_parent.skin.ramp == other.skin.ramp {
            let lo = skin_parent.skin.step.min(other.skin.step) as i32;
            let hi = skin_parent.skin.step.max(other.skin.step) as i32;
            rng.range_i(lo, hi) as usize
        } else {
            skin_parent.skin.step
        };

        let cloth = Tone {
            ramp: *rng.pick(palette::CLOTH_RAMPS),
            step: rng.range_i(1, 4) as usize,
        };
        let accent = {
            let mut tone = Tone {
                ramp: *rng.pick(palette::CLOTH_RAMPS),
                step: rng.range_i(1, 4) as usize,
            };
            for _ in 0..8 {
                if tone.ramp != cloth.ramp {
                    break;
                }
                tone.ramp = *rng.pick(palette::CLOTH_RAMPS);
            }
            tone
        };

        CreatureGenome {
            species: a.species,
            // An even roll, independent of the parents.
            sex: if rng.chance(0.5) {
                Sex::Female
            } else {
                Sex::Male
            },
            proportions,
            gait,
            skin: Tone {
                ramp: skin_parent.skin.ramp,
                step: skin_step,
            },
            // Clothing, headwear and grooming are cultural, not genetic, so they are
            // re-rolled rather than inherited. When settlements gain doctrine, this
            // is where it will express itself — a village that decides the god
            // favours the drowned will dress differently from one that does not.
            cloth,
            accent,
            hair: if rng.chance(0.5) { a.hair } else { b.hair },
            // A newborn is a child; ageing happens in the simulation, not here.
            age: Age::Child,
            hair_style: *rng.pick(&HairStyle::ALL),
            hair_volume: if rng.chance(0.5) {
                a.hair_volume
            } else {
                b.hair_volume
            },
            beard: false,
            headwear: *rng.pick(&Headwear::ALL),
            garment: *rng.pick(&Garment::ALL),
            belt: rng.chance(0.45),
            trousers: rng.chance(0.5),
            satchel: false,
            horns: if rng.chance(0.5) { a.horns } else { b.horns },
            tail: a.tail,
        }
    }

    /// Total standing height in world units.
    pub fn height(&self) -> f32 {
        let p = &self.proportions;
        let base = match self.species {
            Species::Human => 1.75,
            Species::Deer => 1.5,
            Species::Wolf => 1.0,
            Species::Boar => 0.95,
        };
        // Age scales the finished height rather than being folded into `scale`, so
        // an inherited `scale` always means "size as an adult". Otherwise a child's
        // own smallness would be passed on to its children and the line would shrink
        // every generation.
        base * p.scale * self.age.height_scale()
    }

    /// Limb and torso thickness in world units.
    pub fn thickness(&self) -> f32 {
        let p = &self.proportions;
        self.height() * (0.07 + p.build * 0.05)
    }

    /// Walking speed in world units per second.
    pub fn walk_speed(&self) -> f32 {
        self.species.base_speed() * self.proportions.scale * self.gait.stride_rate * self.age.pace()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample(species: Species, seed: u64) -> CreatureGenome {
        CreatureGenome::random(species, &mut Rng::new(seed))
    }

    #[test]
    fn women_are_never_bearded_and_grown_men_often_are() {
        let mut bearded_men = 0;
        for seed in 0..300 {
            let g = sample(Species::Human, seed);
            match g.sex {
                Sex::Female => assert!(!g.beard, "a bearded woman at seed {seed}"),
                Sex::Male if g.age != Age::Child && g.beard => bearded_men += 1,
                Sex::Male => {}
            }
        }
        assert!(bearded_men > 20, "only {bearded_men} bearded men in 300");
    }

    #[test]
    fn both_sexes_are_born_in_roughly_even_measure() {
        let mother = sample(Species::Human, 1);
        let father = sample(Species::Human, 2);
        let mut rng = Rng::new(9);
        let mut daughters = 0;
        for _ in 0..200 {
            let child = CreatureGenome::child_of(&mother, &father, &mut rng);
            if child.sex == Sex::Female {
                daughters += 1;
            }
        }
        assert!(
            (60..=140).contains(&daughters),
            "{daughters} daughters of 200",
        );
    }

    #[test]
    fn generation_is_deterministic() {
        let a = sample(Species::Human, 5);
        let b = sample(Species::Human, 5);
        assert_eq!(a.height(), b.height());
        assert_eq!(a.skin, b.skin);
    }

    #[test]
    fn every_species_produces_sane_bodies() {
        for species in [Species::Human, Species::Deer, Species::Wolf, Species::Boar] {
            for seed in 0..200 {
                let g = sample(species, seed);
                assert!(g.height() > 0.4 && g.height() < 3.0, "{species:?} height");
                assert!(g.thickness() > 0.0);
                assert!(g.walk_speed() > 0.0);
                assert!(g.proportions.leg_length > 0.0);
                assert!(g.skin.palette_index() < palette::PALETTE_LEN);
                assert!(g.cloth.palette_index() < palette::PALETTE_LEN);
                assert!(g.hair.palette_index() < palette::PALETTE_LEN);
            }
        }
    }

    #[test]
    fn only_humans_are_dressed_and_only_animals_have_tails() {
        for seed in 0..200 {
            let human = sample(Species::Human, seed);
            assert!(!human.tail);

            let wolf = sample(Species::Wolf, seed);
            assert!(wolf.tail);
            assert_eq!(wolf.hair_style, HairStyle::Bald);
            assert_eq!(wolf.headwear, Headwear::None);
            assert!(!wolf.beard && !wolf.belt && !wolf.trousers && !wolf.satchel);
            assert_eq!(wolf.age, Age::Adult);
        }
    }

    #[test]
    fn children_are_smaller_and_never_bearded() {
        let mut children = 0;
        for seed in 0..600 {
            let g = sample(Species::Human, seed);
            if g.age == Age::Child {
                children += 1;
                assert!(!g.beard, "seed {seed}: bearded child");
                assert!(!g.satchel);
            }
        }
        assert!(children > 60, "only {children} children in 600 villagers");
    }

    #[test]
    fn a_settlement_contains_every_life_stage() {
        // A crowd of uniformly adult figures reads as manufactured. Twelve villagers
        // will not always cover all three, but a few hundred must.
        let mut rng = Rng::new(2024);
        let mut saw = [false; 3];
        for _ in 0..300 {
            match CreatureGenome::random(Species::Human, &mut rng).age {
                Age::Child => saw[0] = true,
                Age::Adult => saw[1] = true,
                Age::Elder => saw[2] = true,
            }
        }
        assert!(saw.iter().all(|s| *s), "missing a life stage: {saw:?}");
    }

    #[test]
    fn accent_never_matches_the_main_garment() {
        // Trim, belts and sashes exist to break up the garment. Same ramp and they
        // disappear into it.
        for seed in 0..2_000 {
            let g = sample(Species::Human, seed);
            assert_ne!(g.accent.ramp, g.cloth.ramp, "seed {seed}");
        }
    }

    #[test]
    fn villagers_are_visually_distinct() {
        // The point of all of this: a settlement should not contain twins. Compare
        // the traits that actually read on screen.
        let mut rng = Rng::new(7);
        let mut seen = std::collections::HashSet::new();
        let population = 200;

        for _ in 0..population {
            let g = CreatureGenome::random(Species::Human, &mut rng);
            seen.insert((
                g.age,
                g.hair_style,
                g.headwear,
                g.garment,
                g.skin.ramp,
                g.skin.step,
                g.cloth.ramp,
                g.cloth.step,
                g.beard,
                g.trousers,
                g.belt,
            ));
        }

        // Allowing for chance collisions, near-all of them should be unique.
        assert!(
            seen.len() > (population * 9) / 10,
            "only {} distinct villagers out of {population}",
            seen.len(),
        );
    }

    #[test]
    fn children_resemble_their_parents() {
        // A child's height should sit near its parents' rather than anywhere in
        // the species range, otherwise family resemblance will not read on screen.
        let mut rng = Rng::new(1234);
        let mut close = 0;
        let trials = 800;

        for _ in 0..trials {
            let a = CreatureGenome::random(Species::Human, &mut rng);
            let b = CreatureGenome::random(Species::Human, &mut rng);
            let child = CreatureGenome::child_of(&a, &b, &mut rng);

            let parent_mid = (a.height() + b.height()) * 0.5;
            let spread = (a.height() - b.height()).abs().max(0.05);
            // Children are generated at child scale; compare grown-up sizes.
            let grown = child.height() / child.age.height_scale();
            if (grown - parent_mid).abs() <= spread {
                close += 1;
            }
        }

        let fraction = close as f32 / trials as f32;
        // The mutation nudge legitimately carries some children outside their
        // parents' spread; what this guards is the failure mode where height is
        // rolled fresh and the fraction collapses toward the species-wide rate.
        assert!(
            fraction > 0.7,
            "only {fraction} of children resembled parents"
        );
    }

    #[test]
    fn children_stay_within_valid_bounds() {
        let mut rng = Rng::new(99);
        let mut a = CreatureGenome::random(Species::Human, &mut rng);
        let mut b = CreatureGenome::random(Species::Human, &mut rng);

        // Breed many generations deep: drift must not walk the population off a cliff.
        for _ in 0..500 {
            let child = CreatureGenome::child_of(&a, &b, &mut rng);
            assert!(child.height() > 0.3 && child.height() < 3.0);
            assert!(child.proportions.build >= 0.0 && child.proportions.build <= 1.0);
            assert!(child.gait.stride_rate > 0.0);
            assert!(child.skin.palette_index() < palette::PALETTE_LEN);
            a = b;
            b = child;
        }
    }

    #[test]
    fn tone_shifting_stays_inside_the_ramp() {
        let t = Tone {
            ramp: palette::RAMP_GRASS,
            step: 2,
        };
        assert_eq!(t.shifted(-10).step, 0);
        assert_eq!(t.shifted(10).step, palette::RAMP_STEPS - 1);
        assert_eq!(t.shifted(1).step, 3);
        assert_eq!(t.shifted(0).ramp, palette::RAMP_GRASS);
    }
}
